import{S as l,N as c,P as u,K as d,a as p}from"./assets/vendor-D3gR0pi4.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();new l(".skills-swiper",{slidesPerView:6,slidesPerGroup:1,loop:!0,modules:[c,u,d],navigation:{nextEl:".about-skills-btn"},keyboard:{enabled:!0,pageUpDown:!0},mousewheel:{invert:!0},breakpoints:{320:{slidesPerView:2},768:{slidesPerView:3},1440:{slidesPerView:6}}});new l(".swiper",{slidesPerView:4,spaceBetween:16,slidesPerGroup:1,modules:[c,u,d],navigation:{nextEl:".reviews-btn-next",prevEl:".reviews-btn-prev"},keyboard:{enabled:!0,pageUpDown:!0},mousewheel:{invert:!0},breakpoints:{310:{slidesPerView:1},768:{slidesPerView:2},1440:{slidesPerView:4,spaceBetween:10}}});const a={list:document.querySelector(".reviews-list")};document.addEventListener("DOMContentLoaded",async()=>{try{const e=await m(),s=f(e);a.list.innerHTML=s}catch(e){a.list.innerHTML='<p class="reviews-err">---Not found---</p>',console.log(e)}});async function m(){return(await p.get("https://portfolio-js.b.goit.study/api/reviews")).data}function w(e){const{author:s,avatar_url:o,review:i}=e;return`<li class="reviews-item swiper-slide">
              <img
                class="reviews-img"
                src="${o}"
                alt="foto author"
              />
              <h2 class="reviews-name">${s}</h2>
              <p class="reviews-txt">${i}</p>
            </li>`}function f(e){return e.map(w).join("")}(()=>{const e={closeModalBtn:document.querySelector("[data-menu-close]"),modal:document.querySelector("[data-menu]")};console.log(e.closeModalBtn),e.closeModalBtn.addEventListener("click",s);function s(){console.log(e.modal),e.modal.classList.toggle("is-open")}})();document.addEventListener("DOMContentLoaded",function(){const e=document.querySelector(".custom-swiper-prev"),s=document.querySelector(".custom-swiper-next"),o=document.querySelector(".projects-swiper");if(!o||!e||!s)return;const i=new l(o,{slidesPerView:1,spaceBetween:20,grabCursor:!0,allowTouchMove:!0,simulateTouch:!0,touchRatio:1,touchAngle:45,resistance:!0,resistanceRatio:.5,speed:300,loop:!1,navigation:{nextEl:s,prevEl:e},on:{init:function(){t(this)},slideChange:function(){t(this)}}});function t(r){e.disabled=r.isBeginning,s.disabled=r.isEnd,e.classList.toggle("inactive",r.isBeginning),s.classList.toggle("inactive",r.isEnd)}e.addEventListener("click",()=>i.slidePrev()),s.addEventListener("click",()=>i.slideNext())});
//# sourceMappingURL=index.js.map
